services:
  leetcode_api:
    build:
      context: ./leetcode-api
      dockerfile: Dockerfile.dev
    container_name: leetcode-api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REDIS_HOST=redis  
      - REDIS_PORT=6379  
    volumes:
      - ./leetcode-api:/usr/src/app
      - /usr/src/app/node_modules
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - backend-node
    
  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile.dev
    container_name: backend-node
    ports: 
      - "4000:4000"
    depends_on:
      - redis
      - leetcode_api
    environment:
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - MONGO_URI=${MONGO_URI}  # Load from .env file
    env_file:
      - .env
    
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  
