services:
  leetcode_api:
    build:
      context: ./leetcode-api
      dockerfile: Dockerfile
    container_name: leetcode-api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REDIS_HOST=redis  
      - REDIS_PORT=6379  
    volumes:
      - ./leetcode-api:/usr/src/app
      - /usr/src/app/node_modules
    

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-spring
    
  backend-spring:
    build:
      context: ./backend-spring
      dockerfile: Dockerfile
    container_name: backend-spring
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - leetcode_api
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # For external access
    