# --- Stage 1: Build ---
    FROM node:20-alpine AS build
    WORKDIR /usr/src/app
    COPY package*.json ./
    RUN npm install
    COPY . .
    
    # --- Stage 2: Production ---
    FROM node:20-alpine
    WORKDIR /usr/src/app
    COPY package*.json ./
    RUN npm install --production
    COPY --from=build /usr/src/app .
    EXPOSE 3000
    CMD ["npm", "start"]
    